import type { Server } from 'node:http';
import { WebSocket, WebSocketServer } from 'ws';
import { OrderStatus, PaymentMethod, Prisma, ProductStatus } from '../../generated/prisma/client';
import { prisma } from '../config/prisma.js';
import type { RealtimeMessage, RealtimeMetrics, RealtimeOrder } from './types.js';

type AliveSocket = WebSocket & { isAlive?: boolean };
let server: WebSocketServer | undefined;
let heartbeat: NodeJS.Timeout | undefined;
let orderTimer: NodeJS.Timeout | undefined;
let metricsTimer: NodeJS.Timeout | undefined;
const revenueStatuses: OrderStatus[] = [OrderStatus.PAID, OrderStatus.PROCESSING, OrderStatus.SHIPPED, OrderStatus.COMPLETED];
const send = <T>(socket: WebSocket, type: RealtimeMessage<T>['type'], data: T): void => { if (socket.readyState === WebSocket.OPEN) socket.send(JSON.stringify({ type, timestamp: new Date().toISOString(), data } satisfies RealtimeMessage<T>)); };
function broadcast<T>(type: RealtimeMessage<T>['type'], data: T): void { server?.clients.forEach((socket) => send(socket, type, data)); }
function onlineCount(): void { broadcast('ONLINE_COUNT_UPDATED', { count: server?.clients.size ?? 0 }); }
async function createSimulatedOrder(): Promise<RealtimeOrder | null> { const [customer, product] = await Promise.all([prisma.customer.findFirst({ orderBy: { createdAt: 'asc' }, skip: Math.floor(Math.random() * 1_000), select: { id: true, name: true, region: true } }), prisma.product.findFirst({ where: { status: ProductStatus.ACTIVE, stock: { gte: 1 } }, orderBy: { createdAt: 'asc' }, skip: Math.floor(Math.random() * 60), select: { id: true, price: true, cost: true, stock: true } })]); if (!customer || !product) return null; const quantity = Math.min(product.stock, 1 + Math.floor(Math.random() * 3)); const subtotal = new Prisma.Decimal(product.price).mul(quantity); const discount = Math.random() < .25 ? subtotal.mul(.05).toDecimalPlaces(2) : new Prisma.Decimal(0); const totalAmount = subtotal.minus(discount); const now = new Date(); const order = await prisma.$transaction(async (tx) => { const created = await tx.order.create({ data: { orderNumber: `RT-${now.getTime()}-${Math.floor(Math.random() * 1000)}`, customerId: customer.id, region: customer.region, status: 'PAID', paymentMethod: PaymentMethod.CREDIT_CARD, subtotal, discount, totalAmount, items: { create: { productId: product.id, quantity, unitPrice: product.price, costAtSale: product.cost, subtotal } } }, select: { orderNumber: true, totalAmount: true, createdAt: true, status: true } }); await tx.product.update({ where: { id: product.id }, data: { stock: { decrement: quantity } } }); return created; }); return { orderNumber: order.orderNumber, customerName: customer.name, region: customer.region, totalAmount: Number(order.totalAmount.toFixed(2)), createdAt: order.createdAt.toISOString(), status: order.status }; }
async function metrics(): Promise<RealtimeMetrics> { const result = await prisma.order.aggregate({ where: { status: { in: revenueStatuses } }, _count: { id: true }, _sum: { totalAmount: true } }); const count = result._count as { id?: number }; const sums = result._sum as { totalAmount?: Prisma.Decimal | null }; return { totalOrders: count.id ?? 0, totalRevenue: Number(sums.totalAmount?.toFixed(2) ?? 0) }; }
export function initialiseRealtime(httpServer: Server): WebSocketServer { server = new WebSocketServer({ server: httpServer, path: '/ws' }); server.on('connection', (socket: AliveSocket, request) => { socket.isAlive = true; console.info(`WebSocket connected: ${request.socket.remoteAddress ?? 'unknown'}`); send(socket, 'CONNECTION_ESTABLISHED', { message: 'Realtime connection established' }); onlineCount(); socket.on('pong', () => { socket.isAlive = true; }); socket.on('message', (raw) => { try { const message = JSON.parse(raw.toString()) as { type?: string }; if (message.type === 'PING') send(socket, 'PONG', {}); } catch { send(socket, 'ERROR', { message: 'Invalid message' }); } }); socket.on('error', (error) => console.error('WebSocket error:', error.message)); socket.on('close', () => { console.info('WebSocket disconnected'); onlineCount(); }); }); heartbeat = setInterval(() => server?.clients.forEach((socket) => { const client = socket as AliveSocket; if (!client.isAlive) return client.terminate(); client.isAlive = false; client.ping(); }), 30_000); orderTimer = setInterval(() => void createSimulatedOrder().then((order) => { if (order) broadcast('ORDER_CREATED', order); }), 15_000); metricsTimer = setInterval(() => void metrics().then((value) => broadcast('METRICS_UPDATED', value)), 10_000); return server; }
export async function closeRealtime(): Promise<void> { [heartbeat, orderTimer, metricsTimer].forEach((timer) => timer && clearInterval(timer)); await new Promise<void>((resolve) => server?.close(() => resolve()) ?? resolve()); }
