<template><main class="login-page"><section class="login-panel"><div class="login-brand"><span>A</span><p>ANALYTICS<span>OS</span></p></div><div class="login-copy"><p class="overline">WELCOME BACK</p><h1>データプラットフォームにログイン</h1><p>ビジネスデータをつなぎ、成長のシグナルを継続的に把握します。</p></div><el-form ref="formRef" :model="form" :rules="rules" class="login-form" size="large" @submit.prevent="submit"><el-form-item prop="email" label="メールアドレス"><el-input v-model="form.email" placeholder="admin@example.com" autocomplete="email" /></el-form-item><el-form-item prop="password" label="パスワード"><el-input v-model="form.password" type="password" placeholder="パスワードを入力" show-password autocomplete="current-password" @keyup.enter="submit" /></el-form-item><el-button class="login-button" type="primary" :loading="auth.isLoading" native-type="submit">{{ auth.isLoading ? '認証中…' : 'コンソールにログイン' }}</el-button></el-form><p class="login-hint">デモアカウント：admin@example.com · Admin123!</p></section><section class="visual-panel"><div class="visual-orb" /><div class="visual-copy"><p class="overline">E-COMMERCE INTELLIGENCE</p><h2>経営判断を<br><em>さらに速く。</em></h2><p>売上、顧客、商品、リアルタイム運用データを一元化します。</p></div><div class="visual-stats"><span><strong>180</strong>日分の業務データ</span><span><strong>5,000</strong>件のサンプル注文</span></div></section></main></template>

<script setup lang="ts">
import { reactive, ref } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { ElMessage, type FormInstance, type FormRules } from 'element-plus';
import { useAuthStore } from '../stores/auth';
const auth = useAuthStore(); const router = useRouter(); const route = useRoute(); const formRef = ref<FormInstance>(); const form = reactive({ email: 'admin@example.com', password: 'Admin123!' });
const rules: FormRules<typeof form> = { email: [{ required: true, message: 'メールアドレスを入力してください', trigger: 'blur' }, { type: 'email', message: '有効なメールアドレスを入力してください', trigger: 'blur' }], password: [{ required: true, message: 'パスワードを入力してください', trigger: 'blur' }] };
async function submit(): Promise<void> { const valid = await formRef.value?.validate().catch(() => false); if (!valid) return; try { await auth.login(form); ElMessage.success('ログインしました。おかえりなさい'); const redirect = typeof route.query.redirect === 'string' ? route.query.redirect : '/'; await router.replace(redirect); } catch { /* global interceptor reports API errors */ } }
</script>

<style scoped>
.login-page { display: grid; min-height: 100vh; grid-template-columns: minmax(400px, .92fr) minmax(500px, 1.08fr); background: #081426; }.login-panel { display: flex; flex-direction: column; justify-content: center; padding: 64px max(8vw, 48px); background: #0b192d; }.login-brand { display: flex; align-items: center; gap: 9px; position: absolute; top: 30px; }.login-brand > span { display: grid; place-items: center; width: 30px; height: 30px; border-radius: 9px; font-size: 14px; font-weight: 800; color: #fff; background: linear-gradient(145deg, #38c7ff, #5968ff); }.login-brand p { color: #eff8ff; font-weight: 800; font-size: 13px; letter-spacing: .1em; }.login-brand p span { color: #62d7ff; }.login-copy { max-width: 365px; }.overline { color: #4cc9f6; font-size: 10px; letter-spacing: .16em; font-weight: 700; }.login-copy h1 { margin: 10px 0; color: #f1f8ff; font-size: clamp(28px, 3vw, 38px); letter-spacing: -.045em; }.login-copy > p:last-child { color: #849fb9; font-size: 14px; line-height: 1.75; }.login-form { max-width: 365px; margin-top: 35px; }.login-form :deep(.el-form-item__label) { color: #b8cde0; font-size: 12px; }.login-form :deep(.el-input__wrapper) { min-height: 43px; background: rgba(20, 48, 80, .55); box-shadow: 0 0 0 1px rgba(133, 184, 227, .16) inset; }.login-form :deep(.el-input__inner) { color: #e9f5ff; }.login-button { width: 100%; height: 45px; margin-top: 8px; border: 0; background: linear-gradient(105deg, #20b7f2, #5868e9); }.login-hint { max-width: 365px; margin-top: 17px; color: #63809c; font-size: 11px; }.visual-panel { position: relative; overflow: hidden; display: flex; flex-direction: column; justify-content: center; padding: 10vw; background: radial-gradient(circle at 65% 35%, #153c68 0, #0a1d37 40%, #071426 75%); }.visual-panel::before { position: absolute; inset: 0; content: ''; background-image: linear-gradient(rgba(83, 170, 232, .05) 1px, transparent 1px), linear-gradient(90deg, rgba(83, 170, 232, .05) 1px, transparent 1px); background-size: 48px 48px; }.visual-orb { position: absolute; top: 21%; right: 9%; width: min(27vw, 340px); aspect-ratio: 1; border: 1px solid rgba(94, 215, 255, .32); border-radius: 50%; box-shadow: 0 0 0 45px rgba(51, 164, 239, .04), 0 0 0 95px rgba(62, 116, 255, .03), 0 0 80px rgba(38, 170, 250, .24); }.visual-copy, .visual-stats { position: relative; }.visual-copy h2 { margin: 16px 0; color: #f0f8ff; font-size: clamp(38px, 4.5vw, 64px); line-height: 1.08; letter-spacing: -.06em; }.visual-copy h2 em { color: #64d9ff; font-style: normal; }.visual-copy > p:last-child { max-width: 330px; color: #98b6ce; font-size: 15px; line-height: 1.8; }.visual-stats { display: flex; gap: 40px; margin-top: 70px; color: #87a8c4; font-size: 12px; }.visual-stats strong { display: block; margin-bottom: 6px; color: #eaf7ff; font-size: 21px; }
@media (max-width: 900px) { .login-page { grid-template-columns: 1fr; }.visual-panel { display: none; }.login-panel { min-height: 100vh; padding: 80px max(8vw, 30px) 40px; } }
</style>
