<template><section class="product-page"><div class="heading"><div><p class="overline">PRODUCT INTELLIGENCE</p><h1>商品分析</h1><p>商品パフォーマンス、在庫リスク、滞留在庫を確認します。</p></div><div class="filters"><el-select v-model="categoryId" clearable placeholder="すべてのカテゴリ" @change="loadAnalysis"><el-option v-for="category in categories" :key="category.id" :label="category.name" :value="category.id" /></el-select><el-input v-model="searchDraft" placeholder="商品名で検索" clearable @keyup.enter="searchProducts"><template #append><el-button @click="searchProducts">検索</el-button></template></el-input><el-button :loading="loading" circle @click="loadAll">↻</el-button><el-button :disabled="!products.length" @click="exportCsv">CSV出力</el-button></div></div><div v-if="error" class="error-state">一部のデータを取得できませんでした。<el-button size="small" type="primary" @click="loadAll">再試行</el-button></div>
<div class="analysis-grid"><article class="surface"><header><div><h2>売れ筋商品 Top 10</h2><p>販売数・売上高・利益で切り替え可能</p></div></header><el-skeleton v-if="loading" animated :rows="9" /><TopProductsBarChart v-else-if="topProducts.length" :data="topProducts" /><div v-else class="empty">商品データはありません</div></article><article class="surface"><header><div><h2>カテゴリ別売上構成</h2><p>支払い済み売上高の構成比</p></div></header><el-skeleton v-if="loading" animated :rows="8" /><CategoryDistributionChart v-else-if="distribution.length" :data="distribution" /><div v-else class="empty">カテゴリデータはありません</div></article></div>
<div class="analysis-grid lower"><article class="surface"><header><div><h2>在庫アラート</h2><p>補充基準を下回るアクティブ商品</p></div></header><el-skeleton v-if="loading" animated :rows="6" /><ul v-else-if="alerts.length" class="alert-list"><li v-for="item in alerts" :key="item.productId"><div><strong>{{ item.productName }}</strong><p>{{ item.categoryName }} · {{ item.sku }}</p></div><span class="stock-danger">在庫 {{ item.stock }} / 基準 {{ item.reorderLevel }}</span></li></ul><div v-else class="empty">在庫アラートはありません</div></article><article class="surface"><header><div><h2>滞留商品</h2><p>30日間の販売数が3件以下、かつ高在庫の商品</p></div></header><el-skeleton v-if="loading" animated :rows="6" /><ul v-else-if="slowMoving.length" class="slow-list"><li v-for="item in slowMoving.slice(0, 6)" :key="item.id"><div><strong>{{ item.name }}</strong><p>{{ item.categoryName }} · 直近30日 {{ item.recentQuantity }}件</p></div><span>在庫 {{ item.stock }}</span></li></ul><div v-else class="empty">滞留商品はありません</div></article></div>
<article class="surface table-surface"><header><div><h2>商品データ明細</h2><p>{{ total }}件中 {{ products.length }}件を表示</p></div></header><el-table :data="products" class="product-table" size="small" v-loading="tableLoading" @sort-change="changeSort"><el-table-column prop="name" label="商品名" min-width="180" sortable="custom" /><el-table-column prop="categoryName" label="カテゴリ" min-width="120" /><el-table-column prop="price" label="価格" min-width="105" align="right" sortable="custom"><template #default="scope">{{ money(scope.row.price) }}</template></el-table-column><el-table-column prop="stock" label="在庫" min-width="94" align="right" sortable="custom"><template #default="scope"><span :class="scope.row.stock < scope.row.reorderLevel ? 'stock-danger' : ''">{{ scope.row.stock }}</span></template></el-table-column><el-table-column prop="status" label="ステータス" min-width="105"><template #default="scope">{{ scope.row.status === 'ACTIVE' ? '有効' : '無効' }}</template></el-table-column></el-table><div class="pagination"><el-pagination v-model:current-page="page" :page-size="pageSize" layout="total, prev, pager, next" :total="total" @current-change="loadProducts" /></div></article></section></template>

<script setup lang="ts">
import dayjs from 'dayjs';
import { onMounted, ref } from 'vue';
import type { TableColumnCtx } from 'element-plus';
import CategoryDistributionChart from '../components/charts/CategoryDistributionChart.vue'; import TopProductsBarChart from '../components/charts/TopProductsBarChart.vue';
import { getCategoryDistribution, getInventoryAlerts, getProductCategories, getProductList, getSlowMovingProducts, getTopProducts } from '../api/dashboard';
import type { CategoryDistribution, InventoryAlert, ProductCategory, ProductListItem, SlowMovingProduct, TopProduct } from '../types/dashboard';
const categories = ref<ProductCategory[]>([]); const categoryId = ref<string>(); const searchDraft = ref(''); const search = ref(''); const page = ref(1); const pageSize = 10; const total = ref(0); const sortBy = ref<'name' | 'price' | 'stock' | 'createdAt'>('name'); const sortOrder = ref<'asc' | 'desc'>('asc'); const loading = ref(false); const tableLoading = ref(false); const error = ref(false); const topProducts = ref<TopProduct[]>([]); const distribution = ref<CategoryDistribution[]>([]); const alerts = ref<InventoryAlert[]>([]); const slowMoving = ref<SlowMovingProduct[]>([]); const products = ref<ProductListItem[]>([]);
const productParams = () => ({ categoryId: categoryId.value, search: search.value || undefined, page: page.value, pageSize, sortBy: sortBy.value, sortOrder: sortOrder.value }); const categoryParams = () => ({ categoryId: categoryId.value }); const analyticsParams = () => ({ ...categoryParams(), startDate: dayjs().subtract(29, 'day').format('YYYY-MM-DD'), endDate: dayjs().format('YYYY-MM-DD') });
async function loadAnalysis(): Promise<void> { if (loading.value) return; loading.value = true; error.value = false; const results = await Promise.allSettled([getTopProducts(analyticsParams(), 10), getCategoryDistribution(analyticsParams()), getInventoryAlerts(categoryParams()), getSlowMovingProducts(categoryParams())]); const [top, category, inventory, slow] = results; if (top.status === 'fulfilled') topProducts.value = top.value; if (category.status === 'fulfilled') distribution.value = category.value; if (inventory.status === 'fulfilled') alerts.value = inventory.value; if (slow.status === 'fulfilled') slowMoving.value = slow.value; error.value = results.some((result) => result.status === 'rejected'); loading.value = false; page.value = 1; await loadProducts(); }
async function loadProducts(): Promise<void> { tableLoading.value = true; try { const result = await getProductList(productParams()); products.value = result.items; total.value = result.total; } catch { error.value = true; } finally { tableLoading.value = false; } }
async function loadAll(): Promise<void> { await loadAnalysis(); }
function searchProducts(): void { search.value = searchDraft.value.trim(); page.value = 1; void loadProducts(); }
function changeSort({ prop, order }: { prop: string; order: 'ascending' | 'descending' | null; column: TableColumnCtx<ProductListItem> }): void { if (prop !== 'name' && prop !== 'price' && prop !== 'stock') return; sortBy.value = prop; sortOrder.value = order === 'descending' ? 'desc' : 'asc'; page.value = 1; void loadProducts(); }
function money(value: number): string { return new Intl.NumberFormat('ja-JP', { style: 'currency', currency: 'JPY', maximumFractionDigits: 0 }).format(value); }
async function exportCsv(): Promise<void> { const result = await getProductList({ ...productParams(), page: 1, pageSize: 100 }); const rows = [['商品名','SKU','カテゴリ','価格','原価','在庫','補充基準','ステータス'], ...result.items.map((item) => [item.name,item.sku,item.categoryName,item.price,item.cost,item.stock,item.reorderLevel,item.status])]; const text = rows.map((row) => row.map((value) => `"${String(value).replaceAll('"','""')}"`).join(',')).join('\n'); const url = URL.createObjectURL(new Blob([`\uFEFF${text}`], { type: 'text/csv;charset=utf-8' })); const link = document.createElement('a'); link.href = url; link.download = `products_${categoryId.value ?? 'all'}.csv`; link.click(); URL.revokeObjectURL(url); }
onMounted(async () => { categories.value = await getProductCategories(); await loadAll(); });
</script>

<style scoped>
.product-page{padding-top:22px}.heading{display:flex;justify-content:space-between;align-items:flex-end;gap:20px;margin:22px 0 24px}.overline{color:#4bc9f7;font-size:11px;font-weight:700;letter-spacing:.14em}.heading h1{margin:8px 0;color:#eff8ff;font-size:28px}.heading p:last-child,header p{color:#7f9ab4;font-size:13px}.filters{display:flex;flex-wrap:wrap;justify-content:flex-end;gap:8px}.filters :deep(.el-input){width:235px}.filters :deep(.el-select){width:170px}.filters :deep(.el-input__wrapper){background:rgba(38,79,119,.2);box-shadow:0 0 0 1px rgba(120,180,227,.18) inset}.error-state{display:flex;justify-content:center;align-items:center;gap:12px;min-height:46px;margin-bottom:16px;border:1px solid rgba(255,142,162,.24);border-radius:9px;color:#ffa0b3;background:rgba(150,46,71,.12);font-size:12px}.analysis-grid{display:grid;grid-template-columns:minmax(0,1.45fr) minmax(300px,.9fr);gap:16px}.analysis-grid.lower{grid-template-columns:repeat(2,minmax(0,1fr));margin-top:16px}.surface{min-height:310px;padding:20px;border:1px solid rgba(125,181,230,.13);border-radius:13px;background:linear-gradient(135deg,rgba(24,50,82,.88),rgba(14,30,53,.88));box-shadow:0 15px 34px rgba(0,8,20,.18)}header{min-height:44px}header h2{margin:0 0 5px;color:#eaf4fc;font-size:15px}.empty{display:grid;min-height:210px;place-items:center;color:#7894ad;font-size:13px}.alert-list,.slow-list{padding:0;margin:0;list-style:none}.alert-list li,.slow-list li{display:flex;align-items:center;gap:12px;padding:11px 0;border-bottom:1px solid rgba(126,174,218,.1)}.alert-list strong,.slow-list strong{color:#dbeaf6;font-size:12px;font-weight:500}.alert-list p,.slow-list p{margin:4px 0 0;color:#738ea7;font-size:11px}.alert-list span,.slow-list span{margin-left:auto;color:#c7dbeb;font-size:11px;white-space:nowrap}.stock-danger{color:#ff9aaf!important;font-weight:700}.table-surface{min-height:0;margin-top:16px}.product-table{width:100%;--el-table-bg-color:transparent;--el-table-tr-bg-color:transparent;--el-table-header-bg-color:rgba(44,89,130,.14);--el-table-text-color:#b9d0e2;--el-table-header-text-color:#7f9db8;--el-table-border-color:rgba(126,174,218,.1)}.pagination{display:flex;justify-content:flex-end;margin-top:16px}
@media(max-width:1100px){.analysis-grid,.analysis-grid.lower{grid-template-columns:1fr}}@media(max-width:700px){.heading{align-items:flex-start;flex-direction:column}.filters{justify-content:flex-start}.filters :deep(.el-input),.filters :deep(.el-select){width:100%}.surface{padding:16px}}
</style>
