<template>
  <section class="sales-page">
    <div class="heading"><div><p class="overline">SALES PERFORMANCE</p><h1>売上分析</h1><p>期間と粒度を揃え、売上・注文・客単価の変化を確認します。</p></div><div class="filters"><el-date-picker v-model="range" type="daterange" value-format="YYYY-MM-DD" format="YYYY/MM/DD" start-placeholder="開始日" end-placeholder="終了日" :clearable="false" @change="applyFilters" /><el-button-group><el-button v-for="item in granularities" :key="item.key" :type="granularity === item.key ? 'primary' : 'default'" @click="selectGranularity(item.key)">{{ item.label }}</el-button></el-button-group><el-button :loading="loading" circle aria-label="更新" @click="loadData">↻</el-button><el-button :disabled="!trend.length" @click="exportCsv">CSV出力</el-button></div></div>
    <div v-if="error" class="error-state">一部のデータを取得できませんでした。選択した条件は保持されています。<el-button size="small" type="primary" @click="loadData">再試行</el-button></div>
    <div class="summary-grid"><article><span>期間売上高</span><strong>{{ money(overview?.totalRevenue ?? 0) }}</strong><small :class="growthClass(overview?.revenueGrowth ?? 0)">{{ growthArrow(overview?.revenueGrowth ?? 0) }} {{ Math.abs(overview?.revenueGrowth ?? 0).toFixed(1) }}% 前期間比</small></article><article><span>注文数</span><strong>{{ number(overview?.totalOrders ?? 0) }}</strong><small :class="growthClass(overview?.orderGrowth ?? 0)">{{ growthArrow(overview?.orderGrowth ?? 0) }} {{ Math.abs(overview?.orderGrowth ?? 0).toFixed(1) }}% 前期間比</small></article><article><span>平均注文単価</span><strong>{{ money(overview?.averageOrderValue ?? 0) }}</strong><small>支払い済み注文の平均</small></article></div>
    <div class="chart-grid"><article class="surface wide"><header><div><h2>売上高・注文数の推移</h2><p>{{ granularityLabel }}ごとの売上高と注文数</p></div></header><el-skeleton v-if="loading" animated :rows="9" /><SalesTrendChart v-else-if="trend.length" :data="trend" /><div v-else class="empty">選択した条件のデータはありません</div></article><article class="surface"><header><div><h2>平均注文単価の推移</h2><p>{{ granularityLabel }}ごとの平均注文単価</p></div></header><el-skeleton v-if="loading" animated :rows="8" /><MetricLineChart v-else-if="trend.length" :data="aovPoints" title="平均注文単価の推移" :formatter="compactMoney" /><div v-else class="empty">表示できるデータはありません</div></article></div>
    <div class="detail-grid"><article class="surface"><header><div><h2>地域別売上ランキング</h2><p>選択期間の顧客地域別売上高</p></div></header><el-skeleton v-if="loading" animated :rows="7" /><ol v-else-if="regions.length" class="region-list"><li v-for="(region, index) in regions.slice(0, 8)" :key="region.region"><span>{{ index + 1 }}</span><p>{{ region.region }}</p><strong>{{ money(region.revenue) }}</strong></li></ol><div v-else class="empty">地域データはありません</div></article><article class="surface"><header><div><h2>売上データ明細</h2><p>現在のフィルター条件と同じ集計結果</p></div></header><el-table v-if="trend.length" :data="trend" size="small" class="detail-table" max-height="310"><el-table-column prop="date" label="日付" min-width="96" /><el-table-column label="売上高" align="right" min-width="108"><template #default="scope">{{ money(scope.row.revenue) }}</template></el-table-column><el-table-column prop="orderCount" label="注文数" align="right" min-width="78" /><el-table-column label="平均注文単価" align="right" min-width="122"><template #default="scope">{{ money(scope.row.averageOrderValue) }}</template></el-table-column></el-table><div v-else-if="!loading" class="empty">明細データはありません</div></article></div>
  </section>
</template>

<script setup lang="ts">
import dayjs from 'dayjs';
import { computed, onMounted, ref } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import MetricLineChart from '../components/charts/MetricLineChart.vue';
import SalesTrendChart from '../components/charts/SalesTrendChart.vue';
import { getCustomerRegions, getOverview, getSalesTrendByGranularity } from '../api/dashboard';
import type { CustomerRegion, DashboardOverview, DateRangeParams, SalesTrendPoint } from '../types/dashboard';

type Granularity = 'day' | 'week' | 'month';
const route = useRoute(); const router = useRouter(); const now = dayjs();
const range = ref<[string, string]>([typeof route.query.startDate === 'string' ? route.query.startDate : now.subtract(29, 'day').format('YYYY-MM-DD'), typeof route.query.endDate === 'string' ? route.query.endDate : now.format('YYYY-MM-DD')]);
const granularity = ref<Granularity>(route.query.granularity === 'week' || route.query.granularity === 'month' ? route.query.granularity : 'day');
const granularities: { key: Granularity; label: string }[] = [{ key: 'day', label: '日別' }, { key: 'week', label: '週別' }, { key: 'month', label: '月別' }];
const loading = ref(false); const error = ref(false); const overview = ref<DashboardOverview | null>(null); const trend = ref<SalesTrendPoint[]>([]); const regions = ref<CustomerRegion[]>([]);
const granularityLabel = computed(() => granularities.find((item) => item.key === granularity.value)?.label.replace('別', '') ?? '日');
const aovPoints = computed(() => trend.value.map((item) => ({ date: item.date, value: item.averageOrderValue })));
function params(): DateRangeParams { return { startDate: range.value[0], endDate: range.value[1] }; }
async function syncQuery(): Promise<void> { await router.replace({ query: { startDate: range.value[0], endDate: range.value[1], granularity: granularity.value } }); }
async function applyFilters(value?: [string, string] | null): Promise<void> { if (value) range.value = value; await syncQuery(); await loadData(); }
async function selectGranularity(value: Granularity): Promise<void> { if (granularity.value === value) return; granularity.value = value; await syncQuery(); await loadData(); }
async function loadData(): Promise<void> { if (loading.value) return; loading.value = true; error.value = false; const query = params(); const [overviewResult, trendResult, regionsResult] = await Promise.allSettled([getOverview(query), getSalesTrendByGranularity(query, granularity.value), getCustomerRegions(query)]); if (overviewResult.status === 'fulfilled') overview.value = overviewResult.value; if (trendResult.status === 'fulfilled') trend.value = trendResult.value; if (regionsResult.status === 'fulfilled') regions.value = regionsResult.value; error.value = [overviewResult, trendResult, regionsResult].some((result) => result.status === 'rejected'); loading.value = false; }
function money(value: number): string { return new Intl.NumberFormat('ja-JP', { style: 'currency', currency: 'JPY', maximumFractionDigits: 0 }).format(value); }
function compactMoney(value: number): string { return `¥${Intl.NumberFormat('ja-JP', { notation: 'compact', maximumFractionDigits: 1 }).format(value)}`; }
function number(value: number): string { return new Intl.NumberFormat('ja-JP').format(value); }
function growthArrow(value: number): string { return value >= 0 ? '↗' : '↘'; } function growthClass(value: number): string { return value >= 0 ? 'positive' : 'negative'; }
function exportCsv(): void { const quote = (value: string | number) => `"${String(value).replaceAll('"', '""')}"`; const content = [['日付', '売上高', '注文数', '平均注文単価'], ...trend.value.map((item) => [item.date, item.revenue, item.orderCount, item.averageOrderValue])].map((row) => row.map(quote).join(',')).join('\n'); const url = URL.createObjectURL(new Blob([`\uFEFF${content}`], { type: 'text/csv;charset=utf-8' })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `sales-analysis_${range.value[0]}_${range.value[1]}.csv`; anchor.click(); URL.revokeObjectURL(url); }
onMounted(() => { void loadData(); });
</script>

<style scoped>
.sales-page { padding-top: 22px; }.heading { display: flex; justify-content: space-between; align-items: flex-end; gap: 20px; margin: 22px 0 24px; }.overline { color: #4bc9f7; font-size: 11px; font-weight: 700; letter-spacing: .14em; }.heading h1 { margin: 8px 0; color: #eff8ff; font-size: 28px; }.heading p:last-child, header p { color: #7f9ab4; font-size: 13px; }.filters { display: flex; flex-wrap: wrap; justify-content: flex-end; gap: 8px; }.filters :deep(.el-input__wrapper) { background: rgba(38,79,119,.2); box-shadow: 0 0 0 1px rgba(120,180,227,.18) inset; }.filters :deep(.el-range-input), .filters :deep(.el-range-separator) { color: #c1d8eb; }.error-state { display: flex; align-items: center; justify-content: center; gap: 12px; min-height: 46px; margin-bottom: 16px; border: 1px solid rgba(255,142,162,.24); border-radius: 9px; color: #ffa0b3; background: rgba(150,46,71,.12); font-size: 12px; }.summary-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; }.summary-grid article, .surface { border: 1px solid rgba(125,181,230,.13); border-radius: 13px; background: linear-gradient(135deg,rgba(24,50,82,.88),rgba(14,30,53,.88)); box-shadow: 0 15px 34px rgba(0,8,20,.18); }.summary-grid article { padding: 18px; }.summary-grid span, .summary-grid small { color: #809ab3; font-size: 12px; }.summary-grid strong { display: block; margin: 14px 0 7px; color: #ebf7ff; font-size: 24px; }.positive { color: #48d8a4 !important; }.negative { color: #ff9aaf !important; }.chart-grid, .detail-grid { display: grid; grid-template-columns: minmax(0, 1.45fr) minmax(290px, .9fr); gap: 16px; margin-top: 16px; }.detail-grid { grid-template-columns: minmax(260px, .75fr) minmax(0, 1.25fr); }.surface { min-height: 310px; padding: 20px; }header { min-height: 44px; }header h2 { margin: 0 0 5px; color: #eaf4fc; font-size: 15px; }.empty { display: grid; min-height: 215px; place-items: center; color: #7894ad; font-size: 13px; }.region-list { margin: 5px 0 0; padding: 0; list-style: none; }.region-list li { display: flex; align-items: center; gap: 10px; padding: 10px 0; border-bottom: 1px solid rgba(126,174,218,.1); }.region-list span { display: grid; place-items: center; width: 22px; height: 22px; border-radius: 5px; color: #65d4fa; background: rgba(67,183,243,.11); font-size: 10px; }.region-list p { color: #b7cde0; font-size: 12px; }.region-list strong { margin-left: auto; color: #deedf8; font-size: 12px; }.detail-table { width: 100%; --el-table-bg-color: transparent; --el-table-tr-bg-color: transparent; --el-table-header-bg-color: rgba(44,89,130,.14); --el-table-text-color: #b9d0e2; --el-table-header-text-color: #7f9db8; --el-table-border-color: rgba(126,174,218,.1); }
@media (max-width: 1100px) { .chart-grid, .detail-grid { grid-template-columns: 1fr; } }
@media (max-width: 700px) { .heading { align-items: flex-start; flex-direction: column; }.filters { justify-content: flex-start; }.filters :deep(.el-date-editor) { width: 100%; }.summary-grid { grid-template-columns: 1fr; }.surface { padding: 16px; } }
</style>
