import type { Request, Response } from 'express';
import { prisma } from '../config/prisma.js';
import { getSalesTrend } from '../services/analytics.service.js';
import { createCsv } from '../utils/csv.js';
import type { SalesTrendQuery } from '../validators/analytics.validator.js';

function download(response: Response, name: string, csv: string): Response { response.setHeader('Content-Type', 'text/csv; charset=utf-8'); response.setHeader('Content-Disposition', `attachment; filename="${name}"`); return response.send(csv); }
function range(request: Request): { start: Date; end: Date; filename: string } { const start = typeof request.query.startDate === 'string' ? request.query.startDate : new Date(Date.now() - 29 * 86_400_000).toISOString().slice(0, 10); const end = typeof request.query.endDate === 'string' ? request.query.endDate : new Date().toISOString().slice(0, 10); return { start: new Date(`${start}T00:00:00.000Z`), end: new Date(`${end}T23:59:59.999Z`), filename: `${start}_${end}` }; }
export async function salesExportController(_request: Request, response: Response): Promise<Response> { const query = response.locals.validatedInput as SalesTrendQuery; const rows = await getSalesTrend(query); return download(response, `sales-report_${query.startDate.toISOString().slice(0,10)}_${query.endDate.toISOString().slice(0,10)}.csv`, createCsv(['日付','売上高','注文数','平均注文単価'], rows.map((r) => [r.date,r.revenue.toFixed(2),r.orderCount,r.averageOrderValue.toFixed(2)]))); }
export async function productsExportController(request: Request, response: Response): Promise<Response> { const { filename } = range(request); const products = await prisma.product.findMany({ include: { category: true }, orderBy: { name: 'asc' } }); return download(response, `products-report_${filename}.csv`, createCsv(['商品名','SKU','カテゴリ','価格','原価','在庫','補充基準','状態'], products.map((p) => [p.name,p.sku,p.category.name,p.price.toFixed(2),p.cost.toFixed(2),p.stock,p.reorderLevel,p.status]))); }
export async function customersExportController(request: Request, response: Response): Promise<Response> { const { filename } = range(request); const customers = await prisma.customer.findMany({ include: { orders: { where: { status: { in: ['PAID','PROCESSING','SHIPPED','COMPLETED'] } } } }, orderBy: { registrationDate: 'desc' } }); return download(response, `customers-report_${filename}.csv`, createCsv(['顧客名','メール','地域','年齢','性別','会員','登録日','注文数','総消費額'], customers.map((c) => [c.name,c.email,c.region,c.age ?? '',c.gender,c.memberLevel,c.registrationDate.toISOString().slice(0,10),c.orders.length,c.orders.reduce((sum,o)=>sum+Number(o.totalAmount),0).toFixed(2)]))); }
export async function ordersExportController(request: Request, response: Response): Promise<Response> { const { start,end,filename } = range(request); const orders = await prisma.order.findMany({ where: { createdAt: { gte: start, lte: end } }, include: { customer: true }, orderBy: { createdAt: 'desc' } }); return download(response, `orders-report_${filename}.csv`, createCsv(['注文番号','顧客','地域','状態','決済方法','金額','日時'], orders.map((o) => [o.orderNumber,o.customer.name,o.region,o.status,o.paymentMethod,o.totalAmount.toFixed(2),o.createdAt.toISOString()]))); }
