<template><div ref="canvas" class="metric-line" :aria-label="title" /></template>

<script setup lang="ts">
import * as d3 from 'd3';
import { onBeforeUnmount, onMounted, ref, watch } from 'vue';

export type MetricLinePoint = { date: string; value: number };
const props = defineProps<{ data: MetricLinePoint[]; title: string; formatter: (value: number) => string }>();
const canvas = ref<HTMLDivElement>(); let observer: ResizeObserver | undefined; let svg: d3.Selection<SVGSVGElement, unknown, null, undefined> | undefined;
function draw(): void { if (!canvas.value) return; if (!svg) svg = d3.select(canvas.value).append('svg').attr('role', 'img'); if (!props.data.length) { svg.selectAll('*').remove(); return; } const width = Math.max(canvas.value.clientWidth, 280); const height = 220; const margin = { top: 12, right: 12, bottom: 30, left: 60 }; const innerWidth = width - margin.left - margin.right; const innerHeight = height - margin.top - margin.bottom; const x = d3.scaleTime().domain(d3.extent(props.data, (item) => new Date(`${item.date}T00:00:00Z`)) as [Date, Date]).range([0, innerWidth]); const y = d3.scaleLinear().domain([0, Math.max(1, d3.max(props.data, (item) => item.value) ?? 1) * 1.1]).nice().range([innerHeight, 0]); svg.attr('viewBox', `0 0 ${width} ${height}`); const plot = svg.selectAll<SVGGElement, unknown>('.plot').data([null]).join('g').attr('class', 'plot').attr('transform', `translate(${margin.left},${margin.top})`); svg.selectAll<SVGGElement, unknown>('.y-axis').data([null]).join('g').attr('class', 'y-axis').attr('transform', `translate(${margin.left},${margin.top})`).call(d3.axisLeft(y).ticks(4).tickFormat((value) => props.formatter(Number(value)))).call((axis) => axis.selectAll('text').attr('fill', '#7894ad').attr('font-size', 10)).call((axis) => axis.select('.domain').remove()).call((axis) => axis.selectAll('line').attr('x2', innerWidth).attr('stroke', 'rgba(129,177,216,.14)')); svg.selectAll<SVGGElement, unknown>('.x-axis').data([null]).join('g').attr('class', 'x-axis').attr('transform', `translate(${margin.left},${height - margin.bottom})`).call(d3.axisBottom<Date>(x).ticks(Math.min(6, props.data.length)).tickFormat((value) => d3.timeFormat('%m/%d')(value as Date))).call((axis) => axis.selectAll('text').attr('fill', '#7894ad').attr('font-size', 10)).call((axis) => axis.select('.domain').attr('stroke', 'rgba(129,177,216,.18)')); const line = d3.line<MetricLinePoint>().x((item) => x(new Date(`${item.date}T00:00:00Z`))).y((item) => y(item.value)).curve(d3.curveMonotoneX); plot.selectAll<SVGPathElement, MetricLinePoint[]>('.line').data([props.data]).join('path').attr('class', 'line').attr('fill', 'none').attr('stroke', '#5cdbb0').attr('stroke-width', 2.5).transition().duration(350).attr('d', line); }
onMounted(() => { draw(); observer = new ResizeObserver(draw); if (canvas.value) observer.observe(canvas.value); }); onBeforeUnmount(() => { observer?.disconnect(); svg?.remove(); }); watch(() => props.data, draw, { deep: true });
</script>
<style scoped>.metric-line { width: 100%; min-height: 220px; }.metric-line :deep(svg) { display: block; width: 100%; height: auto; overflow: visible; }</style>
