import { computed, onBeforeUnmount, readonly, ref } from 'vue';

export type RealtimeEventType = 'CONNECTION_ESTABLISHED' | 'ORDER_CREATED' | 'METRICS_UPDATED' | 'ONLINE_COUNT_UPDATED' | 'PING' | 'PONG' | 'ERROR';
export type RealtimeEvent<T = unknown> = { type: RealtimeEventType; timestamp: string; data: T };
export type RealtimeOrder = { orderNumber: string; customerName: string; region: string; totalAmount: number; createdAt: string; status: string };
export type RealtimeMetrics = { totalRevenue: number; totalOrders: number };
export type RealtimeActivity = { id: string; message: string; timestamp: string; type: RealtimeEventType };
export type RealtimeSample = { timestamp: string; revenue: number; orders: number };

let activeSocket: WebSocket | undefined;
let activeConsumers = 0;
let reconnectTimer: number | undefined;
const status = ref<'connecting' | 'connected' | 'disconnected' | 'error'>('disconnected');
const onlineCount = ref(0); const metrics = ref<RealtimeMetrics | null>(null); const recentOrders = ref<RealtimeOrder[]>([]); const activities = ref<RealtimeActivity[]>([]); const samples = ref<RealtimeSample[]>([]); const paused = ref(false); const lastMessageAt = ref<string | null>(null); const pending: RealtimeEvent[] = []; let flushTimer: number | undefined;
const socketUrl = (): string => { const configured = import.meta.env.VITE_WS_URL as string | undefined; if (configured) return configured; const protocol = window.location.protocol === 'https:' ? 'wss:' : 'ws:'; return `${protocol}//${window.location.host}/ws`; };
function addActivity(type: RealtimeEventType, message: string, timestamp: string): void { activities.value = [{ id: `${timestamp}-${Math.random()}`, type, message, timestamp }, ...activities.value].slice(0, 50); }
function flush(): void { flushTimer = undefined; if (paused.value) return; const batch = pending.splice(0); batch.forEach((message) => { lastMessageAt.value = message.timestamp; if (message.type === 'ORDER_CREATED') { const order = message.data as RealtimeOrder; recentOrders.value = [order, ...recentOrders.value].slice(0, 50); addActivity(message.type, `新規注文 ${order.orderNumber}（¥${order.totalAmount.toLocaleString('ja-JP')}）`, message.timestamp); } else if (message.type === 'METRICS_UPDATED') { const value = message.data as RealtimeMetrics; metrics.value = value; samples.value = [...samples.value, { timestamp: message.timestamp, revenue: value.totalRevenue, orders: value.totalOrders }].filter((item) => Date.now() - new Date(item.timestamp).getTime() <= 60_000); addActivity(message.type, 'リアルタイム指標を更新しました', message.timestamp); } else if (message.type === 'ONLINE_COUNT_UPDATED') onlineCount.value = Number((message.data as { count: number }).count); else if (message.type === 'CONNECTION_ESTABLISHED') addActivity(message.type, 'リアルタイム接続を確立しました', message.timestamp); }); }
function scheduleFlush(): void { if (!flushTimer) flushTimer = window.setTimeout(flush, 500); }
function connect(): void { if (activeSocket && (activeSocket.readyState === WebSocket.OPEN || activeSocket.readyState === WebSocket.CONNECTING)) return; status.value = 'connecting'; activeSocket = new WebSocket(socketUrl()); activeSocket.onopen = () => { status.value = 'connected'; }; activeSocket.onmessage = (event) => { try { const message = JSON.parse(event.data) as RealtimeEvent; if (message.type === 'PING') { activeSocket?.send(JSON.stringify({ type: 'PONG' })); return; } pending.push(message); scheduleFlush(); } catch { addActivity('ERROR', 'リアルタイムメッセージの解析に失敗しました', new Date().toISOString()); } }; activeSocket.onerror = () => { status.value = 'error'; }; activeSocket.onclose = () => { activeSocket = undefined; if (activeConsumers > 0) { status.value = 'disconnected'; const delay = Math.min(30_000, 1_000 * 2 ** Math.min(6, activities.value.length)); reconnectTimer = window.setTimeout(connect, delay); } }; }
function disconnect(): void { if (reconnectTimer) window.clearTimeout(reconnectTimer); activeSocket?.close(); activeSocket = undefined; status.value = 'disconnected'; }
function setPaused(value: boolean): void { paused.value = value; if (!value && pending.length) flush(); } function clearActivities(): void { activities.value = []; recentOrders.value = []; }
export function useWebSocket() { activeConsumers += 1; connect(); onBeforeUnmount(() => { activeConsumers = Math.max(0, activeConsumers - 1); if (activeConsumers === 0) { if (flushTimer) window.clearTimeout(flushTimer); disconnect(); } }); return { status: readonly(status), isConnected: computed(() => status.value === 'connected'), onlineCount: readonly(onlineCount), metrics: readonly(metrics), recentOrders: readonly(recentOrders), activities: readonly(activities), samples: readonly(samples), paused: readonly(paused), lastMessageAt: readonly(lastMessageAt), connect, disconnect, setPaused, clearActivities }; }
