import { Prisma } from '../../generated/prisma/client'; import { prisma } from '../config/prisma.js'; import type { CustomerListQuery } from '../validators/customer.validator.js';
type Row = Record<string, string | number | bigint | Prisma.Decimal | null>; const n = (v: Row[string] | undefined) => v == null ? 0 : Number(v); const m = (v: Row[string] | undefined) => Number(n(v).toFixed(2));
export type Distribution = { label: string; count: number }; export type CustomerSummary = { newCustomerCount: number; existingCustomerCount: number; averageSpend: number; repeatPurchaseRate: number; ageDistribution: Distribution[]; genderDistribution: Distribution[]; memberLevelDistribution: Distribution[] };
export type HighValueCustomer = { id: string; name: string; email: string; totalSpend: number; orderCount: number; lastPurchaseAt: string | null; rfmScore: number };
export type CustomerListItem = { id: string; name: string; email: string; region: string; age: number | null; gender: string; memberLevel: string; registrationDate: string; totalSpend: number; orderCount: number; lastPurchaseAt: string | null }; export type CustomerListResult = { items: CustomerListItem[]; total: number; page: number; pageSize: number };
export async function getCustomerSummary(): Promise<CustomerSummary> { const [counts, spend, ages, genders, levels] = await Promise.all([
  prisma.$queryRaw<Row[]>(Prisma.sql`SELECT COUNT(*) FILTER (WHERE "registrationDate" >= NOW() - INTERVAL '30 days')::int AS new, COUNT(*) FILTER (WHERE "registrationDate" < NOW() - INTERVAL '30 days')::int AS existing FROM "Customer"`),
  prisma.$queryRaw<Row[]>(Prisma.sql`WITH customer_orders AS (SELECT c.id, COUNT(o.id) FILTER (WHERE o.status IN ('PAID','PROCESSING','SHIPPED','COMPLETED'))::int AS orders, COALESCE(SUM(o."totalAmount") FILTER (WHERE o.status IN ('PAID','PROCESSING','SHIPPED','COMPLETED')),0) AS spend FROM "Customer" c LEFT JOIN "Order" o ON o."customerId"=c.id GROUP BY c.id) SELECT COALESCE(AVG(spend),0) AS avg, COUNT(*) FILTER (WHERE orders >= 2)::int AS repeat, COUNT(*)::int AS total FROM customer_orders`),
  prisma.$queryRaw<Row[]>(Prisma.sql`SELECT CASE WHEN age IS NULL THEN '未設定' WHEN age < 25 THEN '18-24' WHEN age < 35 THEN '25-34' WHEN age < 45 THEN '35-44' WHEN age < 55 THEN '45-54' ELSE '55+' END AS label, COUNT(*)::int AS count FROM "Customer" GROUP BY label ORDER BY label`),
  prisma.$queryRaw<Row[]>(Prisma.sql`SELECT gender::text AS label, COUNT(*)::int AS count FROM "Customer" GROUP BY gender ORDER BY count DESC`),
  prisma.$queryRaw<Row[]>(Prisma.sql`SELECT "memberLevel"::text AS label, COUNT(*)::int AS count FROM "Customer" GROUP BY "memberLevel" ORDER BY count DESC`),
 ]); return { newCustomerCount:n(counts[0]?.new), existingCustomerCount:n(counts[0]?.existing), averageSpend:m(spend[0]?.avg), repeatPurchaseRate:n(spend[0]?.total) ? Number((n(spend[0]?.repeat)/n(spend[0]?.total)*100).toFixed(2)) : 0, ageDistribution:ages.map(r=>({label:String(r.label),count:n(r.count)})), genderDistribution:genders.map(r=>({label:String(r.label),count:n(r.count)})), memberLevelDistribution:levels.map(r=>({label:String(r.label),count:n(r.count)})) }; }
export async function getHighValueCustomers(): Promise<HighValueCustomer[]> { const rows = await prisma.$queryRaw<Row[]>(Prisma.sql`WITH metrics AS (SELECT c.id,c.name,c.email,COALESCE(SUM(o."totalAmount") FILTER (WHERE o.status IN ('PAID','PROCESSING','SHIPPED','COMPLETED')),0) AS spend,COUNT(o.id) FILTER (WHERE o.status IN ('PAID','PROCESSING','SHIPPED','COMPLETED') )::int AS orders,MAX(o."createdAt") FILTER (WHERE o.status IN ('PAID','PROCESSING','SHIPPED','COMPLETED')) AS last FROM "Customer" c LEFT JOIN "Order" o ON o."customerId"=c.id GROUP BY c.id), scored AS (SELECT *, NTILE(5) OVER (ORDER BY spend) + NTILE(5) OVER (ORDER BY orders) + NTILE(5) OVER (ORDER BY last NULLS FIRST) AS score FROM metrics) SELECT id,name,email,spend,orders,last,score FROM scored ORDER BY score DESC, spend DESC LIMIT 10`); return rows.map(r=>({id:String(r.id),name:String(r.name),email:String(r.email),totalSpend:m(r.spend),orderCount:n(r.orders),lastPurchaseAt:r.last ? new Date(String(r.last)).toISOString():null,rfmScore:n(r.score)})); }
export async function getCustomers(query: CustomerListQuery): Promise<CustomerListResult> { const where: Prisma.CustomerWhereInput=query.search?{OR:[{name:{contains:query.search,mode:'insensitive'}},{email:{contains:query.search,mode:'insensitive'}}]}:{}; const [total,customers]=await prisma.$transaction([prisma.customer.count({where}),prisma.customer.findMany({where,skip:(query.page-1)*query.pageSize,take:query.pageSize,orderBy:{registrationDate:'desc'},select:{id:true,name:true,email:true,region:true,age:true,gender:true,memberLevel:true,registrationDate:true,orders:{where:{status:{in:['PAID','PROCESSING','SHIPPED','COMPLETED']}},select:{totalAmount:true,createdAt:true}}}})]); return {total,page:query.page,pageSize:query.pageSize,items:customers.map(c=>({id:c.id,name:c.name,email:c.email,region:c.region,age:c.age,gender:c.gender,memberLevel:c.memberLevel,registrationDate:c.registrationDate.toISOString(),totalSpend:Number(c.orders.reduce((s,o)=>s+Number(o.totalAmount),0).toFixed(2)),orderCount:c.orders.length,lastPurchaseAt:c.orders.sort((a,b)=>b.createdAt.getTime()-a.createdAt.getTime())[0]?.createdAt.toISOString()??null}))}; }
